;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="interact",DevComment="")
GameplayTagList=(Tag="interact.prop.crate_00",DevComment="")
GameplayTagList=(Tag="interact.prop.cube_00",DevComment="")
GameplayTagList=(Tag="interact.prop.cup_00",DevComment="")

